In [1]:
from sklearn.preprocessing import OneHotEncoder

In [2]:
import numpy as np
import pandas as pd

In [21]:
train = [['Red'], ['Blue'],['Green']]

In [22]:
enc = OneHotEncoder(handle_unknown='ignore')


In [26]:
train_transform = enc.fit_transform(train).toarray()

In [27]:
train_transform

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

## Properly coded
- Fit_transform only called on train data and transform called on test and validation

In [35]:
# Encode
enc = OneHotEncoder(handle_unknown='ignore')
train = [['Red', 1], ['Blue', 3], ['Green', 2]]
test = [['Red', 1], ['Blue', 2], ['Green', 2]]
val = [['Red', 1], ['Yellow', 3]] # Contains unseen class

#Fit and transform
train_transform = enc.fit_transform(train).toarray()
test_transform = enc.transform(test).toarray()
val_transform = enc.transform(val).toarray()

#Ouptut
print(f'Train shape: {train_transform.shape} \n{train_transform}')
print(f'\nTest shape: {test_transform.shape} \n{test_transform}')
print(f'\nVal shape: {val_transform.shape} \n{val_transform}')

Train shape: (3, 6) 
[[0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]]

Test shape: (3, 6) 
[[0. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]]

Val shape: (2, 6) 
[[0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


## Calling fit_transform at all stages

**Notice when fit_transform is called on all datasets that we now have a mismatch in columns between training and validation**

In [29]:
lis = ["tommy","frank"]

In [30]:
"..".join(lis)

'tommy..frank'